$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'gmagick'
FILES_PATH = File.dirname(__FILE__) + '/files'
SRC_PATH = FILES_PATH + '/src'
DICE_PATH = SRC_PATH + '/dice.png'
FLOWER_PATH = SRC_PATH + '/flower.jpg'
EARTH_PATH = SRC_PATH + '/earth.gif'
DST_PATH = FILES_PATH + '/dst'
DICE2_PATH = DST_PATH + '/dice2.png'
DICE_ROTATE_PATH = DST_PATH + '/dice_rotate.png'
DICE_ROTATE2_PATH = DST_PATH + '/dice_rotate2.png'
DICE_DRAW_PATH = DST_PATH + '/dice_draw.png'
DICE_RESAMPLE_PATH = DST_PATH + '/dice_resample.png'
DICE_FLIP_PATH = DST_PATH + '/dice_flip.png'
DICE_FLOP_PATH = DST_PATH + '/dice_flop.png'
DICE_CROP_PATH = DST_PATH + '/dice_crop.png'
DICE_BORDER_PATH = DST_PATH + '/dice_border.png'
DICE_FRAME_PATH = DST_PATH + '/dice_frame.png'
DICE_BLUR_PATH = DST_PATH + '/dice_blur.png'
DICE_SWIRL_PATH = DST_PATH + '/dice_swirl.png'
DICE_CHARCOAL_PATH = DST_PATH + '/dice_charcoal.png'
DICE_OIL_PAINT_PATH = DST_PATH + '/dice_oil_paint.png'
