$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'gmagick'
FILES_PATH = File.dirname(__FILE__) + '/files'
SRC_PATH = FILES_PATH + '/src'
DICE_PATH = SRC_PATH + '/dice.png'
FLOWER_PATH = SRC_PATH + '/flower.jpg'
EARTH_PATH = SRC_PATH + '/earth.gif'
DST_PATH = FILES_PATH + '/dst'
DICE2_PATH = DST_PATH + '/dice2.png'
DICE_ROTATE_PATH = DST_PATH + '/dice_rotate.png'