$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'gmagick'
FILES_PATH = File.dirname(__FILE__) + '/files'
SRC_PATH = FILES_PATH + '/src'
DICE_PATH = SRC_PATH + '/dice.png'
FLOWER_PATH = SRC_PATH + '/flower.jpg'
EARTH_PATH = SRC_PATH + '/earth.gif'
DST_PATH = FILES_PATH + '/dst'
DICE2_PATH = DST_PATH + '/dice2.png'
DICE_ROTATE_PATH = DST_PATH + '/dice_rotate.png'
DICE_ROTATE2_PATH = DST_PATH + '/dice_rotate2.png'
DICE_DRAW_PATH = DST_PATH + '/dice_draw.png'
DICE_RESAMPLE_PATH = DST_PATH + '/dice_resample.png'
DICE_FLIP_PATH = DST_PATH + '/dice_flip.png'
DICE_FLOP_PATH = DST_PATH + '/dice_flop.png'
DICE_CROP_PATH = DST_PATH + '/dice_crop.png'